import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { AppTopbar } from "@/components/app-topbar"
import { ThemeProvider } from "@/components/theme-provider"
import { ShortsNavigator } from "@/components/shorts-navigator";
import { ShortsActions } from "@/components/shorts-actions";

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-svh bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <SidebarProvider style={{
            "--sidebar-width": "10rem"
          }}>
            <AppSidebar />
            <main className="flex min-h-svh flex-1 flex-col bg-sidebar">
              <AppTopbar />
              <div id="content-wrapper" className="flex flex-row flex-1 items-center gap-4 md:pr-4 md:pb-4">
                <div id="rounded-container" className="relative flex flex-1 h-full h-col rounded-t-3xl md:rounded-3xl bg-background">
                  {children}
                  <div className="absolute bottom-4 right-4">
                    <ShortsActions />
                  </div>
                </div>
                <ShortsNavigator />
              </div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
