import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { AppTopbar } from "@/components/app-topbar";
import { ThemeProvider } from "@/components/theme-provider";
import {
  ShortsNavProvider,
  ShortsNavigatorPresenter,
} from "@/components/shorts-nav-context";

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-svh bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ShortsNavProvider>
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "10rem",
                } as React.CSSProperties
              }
            >
              <AppSidebar />
              <main className="flex h-svh max-h-svh flex-1 flex-col overflow-hidden bg-sidebar">
                <AppTopbar />
                <div
                  id="content-wrapper"
                  className="flex min-h-0 flex-row flex-1 items-center gap-4 overflow-hidden"
                >
                  <div className="flex min-h-0 h-full w-full flex-1">
                    {children}
                  </div>

                  <ShortsNavigatorPresenter className="hidden md:flex h-full min-h-0 items-center mr-4" />
                </div>
              </main>
            </SidebarProvider>
          </ShortsNavProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
